[package]
name = "matrix-eyes"
version = "0.1.1"
edition = "2024"
authors = ["Dmitry Zolotukhin <zlogic@gmail.com>"]
repository = "https://github.com/zlogic/matrix-eyes"
license = "Apache-2.0"
rust-version = "1.85"

[dependencies]
# Using a custom version to address two issues:
# 1. matmul and nchw_to_nhwc panicked instead of returning an error.
# 2. Autotune for conv2d can run autotune for matmul, and img2col increased the tile size so much it failed for all use cases.
burn = { version = "0.17", git = "https://github.com/zlogic/burn", rev = "b2af9f2e0798a3ee53e6f3766eab0d0dc029e438", default-features = false, features = ["std"] }
burn-import = { version = "0.17", git = "https://github.com/zlogic/burn", rev = "b2af9f2e0798a3ee53e6f3766eab0d0dc029e438", default-features = false, features = ["pytorch"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
kamadak-exif = { version = "0.6", default-features = false }
indicatif = { version = "0.17", default-features = false }
rand = { version = "*", features = ["std", "std_rng", "small_rng"] }
candle-core = { version = "*", optional = true, features = ["cudnn"] }

[features]
default = ["wgpu"]
ndarray = ["burn/ndarray"]
ndarray-accelerate = ["burn/ndarray", "burn/accelerate"]
candle-cuda = ["burn/candle-cuda", "dep:candle-core"]
candle-metal = ["burn/candle", "burn/metal"]
wgpu = ["burn/wgpu", "burn/fusion", "burn/autotune"]
wgpu-spirv = ["burn/vulkan", "burn/fusion", "burn/autotune"]
cuda = ["burn/cuda", "burn/fusion", "burn/autotune"]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
