[package]
name = "matrix-eyes"
version = "0.1.0"
edition = "2021"
authors = ["Dmitry Zolotukhin <zlogic@gmail.com>"]
repository = "https://github.com/zlogic/matrix-eyes"
license = "Apache-2.0"
rust-version = "1.77"

[dependencies]
burn = { version = "0.16", default-features = false, features = ["autotune"] }
burn-import = { version = "0.16", default-features = false, features = ["pytorch"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
kamadak-exif = { version = "0.6", default-features = false }
candle-core = { version = "*", optional = true, features = ["cudnn"] }

[features]
default = ["wgpu"]
ndarray = ["burn/ndarray"]
ndarray-accelerate = ["burn/ndarray", "burn/accelerate"]
candle-cuda = ["burn/candle-cuda", "dep:candle-core"]
# add ndarray to fix a fusion-->ndarray-->rayon-->burn-core feature flag
wgpu = ["burn/wgpu", "burn/fusion", "burn/ndarray"]
wgpu-spirv = ["burn/wgpu-spirv", "burn/fusion", "burn/ndarray"]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
