[package]
name = "matrix-eyes"
version = "0.1.7"
edition = "2024"
authors = ["Dmitrii Zolotukhin <contact@3d-net.nl>"]
repository = "https://github.com/zlogic/matrix-eyes"
license = "Apache-2.0"
rust-version = "1.95"

[dependencies]
burn = { version = "0.22.0-pre.3", default-features = false, features = ["std", "store", "extension"] }
burn-store = { version = "0.22.0-pre.3", default-features = false, features = ["std", "pytorch"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
kamadak-exif = { version = "0.6", default-features = false }
indicatif = { version = "0.18", default-features = false }
rand = { version = "*", features = ["std", "std_rng", "thread_rng"] }

[features]
default = ["flex"]
autotune = ["burn/autotune"]
fusion = ["burn/fusion"]
flex = ["burn/flex"]
wgpu-metal = ["burn/metal"]
wgpu-spirv = ["burn/vulkan"]
cuda = ["burn/cuda"]
f16 = []
bf16 = []

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
