[package]
name = "matrix-eyes"
version = "0.1.0"
edition = "2021"
authors = ["Dmitry Zolotukhin <zlogic@gmail.com>"]
repository = "https://github.com/zlogic/matrix-eyes"
license = "Apache-2.0"
rust-version = "1.77"

[dependencies]
burn = { version = "0.16", default-features = false, features = ["std", "autotune"] }
burn-import = { version = "0.16", default-features = false, features = ["pytorch"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
kamadak-exif = { version = "0.6", default-features = false }

[features]
default = ["wgpu"]
ndarray = ["burn/ndarray"]
wgpu = ["burn/wgpu"]
candle = ["burn/candle"]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
