name: Cargo build

on:
  push:
    branches: [ "main", "rust" ]
  pull_request:
    branches: [ "main", "rust" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4

    - name: Get current Rust version
      id: get-rust-version
      run: echo VERSION=$(rustc --version | sed s/\ /_/g) >> "$GITHUB_OUTPUT"

    - name: Cache Rust dependencies and artifacts
      id: cache-rust
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ${{ github.workspace }}/target
        key: lint-${{ runner.os }}-${{ steps.get-rust-version.outputs.VERSION }}-${{ hashFiles('Cargo.*') }}

    - name: Validate Rust code with clippy
      run: cargo clippy

  build-linux:
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      fail-fast: true
      matrix:
        include:
        - arch: x86_64
          os: ubuntu
        - arch: aarch64
          os: ubuntu

    steps:
    - uses: actions/checkout@v4

    - name: Get current Rust version
      id: get-rust-version
      run: echo VERSION=$(rustc --version | sed s/\ /_/g) >> "$GITHUB_OUTPUT"

    - name: Cache Rust dependencies and artifacts
      id: cache-rust
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ${{ github.workspace }}/target
        key: rust-${{ runner.os }}-${{ matrix.os }}-${{ matrix.arch }}-${{ steps.get-rust-version.outputs.VERSION }}-${{ hashFiles('Cargo.*') }}

    - name: Install compiler and prepare for cross-compilation
      if: matrix.arch == 'aarch64'
      run: |
        rustup target add ${{ matrix.arch }}-unknown-linux-gnu
        sudo apt-get update
        sudo apt-get install -y crossbuild-essential-arm64 qemu-user-static
        echo "LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CC=/usr/bin/aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX=/usr/bin/aarch64-linux-gnu-g++" >> $GITHUB_ENV
        echo "CFLAGS=-march=armv8.2-a" >> $GITHUB_ENV
        echo "CXXFLAGS=-march=armv8.2-a" >> $GITHUB_ENV

    - name: Install CUDA
      if: matrix.arch == 'x86_64'
      run: |
        conda install 'nvidia::cuda'
        echo "ENABLED_FEATURES=cuda" >> $GITHUB_ENV

    - name: Build
      run: cargo build --target=${{ matrix.arch }}-unknown-linux-gnu --features=$ENABLED_FEATURES --release

    - name: Package application
      run: tar -cvjf matrix-eyes-${{ matrix.os }}-${{ matrix.arch }}.tar.bz2 -C target/${{ matrix.arch }}-unknown-linux-gnu/release matrix-eyes

    - name: Upload application
      uses: actions/upload-artifact@v4
      with:
        name: matrix-eyes-${{ matrix.os }}-${{ matrix.arch }}
        path: matrix-eyes-*.tar.bz2

  build-windows:
    runs-on: windows-latest
    needs: validate
    strategy:
      fail-fast: true
      matrix:
        arch: [aarch64, x86_64]

    steps:
    - uses: actions/checkout@v4

    - name: Get current Rust version
      id: get-rust-version
      run: |
        $version = rustc --version | % {$_.replace(" ","_")}
        echo "VERSION=$version" >> "$env:GITHUB_OUTPUT"

    - name: Cache Rust dependencies and artifacts
      id: cache-rust
      uses: actions/cache@v4
      with:
        path: |
          ~\.cargo\registry\index
          ~\.cargo\registry\cache
          ~\.cargo\git\db
          ${{ github.workspace }}\target
        key: rust-${{ runner.os }}-${{ matrix.arch }}-${{ steps.get-rust-version.outputs.VERSION }}-${{ hashFiles('Cargo.*') }}

    - name: Install compiler and prepare for cross-compilation
      if: matrix.arch == 'aarch64'
      run: rustup target add ${{ matrix.arch }}-pc-windows-msvc

    - name: Install CUDA
      if: matrix.arch == 'x86_64'
      run: |
        conda install 'nvidia::cuda'
        echo "ENABLED_FEATURES=cuda" >> $GITHUB_ENV

    - name: Build
      run: |
        $Env:RUSTFLAGS = "-C target-feature=+crt-static"
        cargo build --target=${{ matrix.arch }}-pc-windows-msvc --features=${ENABLED_FEATURES} --release

    - name: Package application
      run: Compress-Archive -Path .\target\${{ matrix.arch }}-pc-windows-msvc\release\matrix-eyes.exe -DestinationPath matrix-eyes-${{ runner.os }}-${{ matrix.arch }}.zip

    - name: Upload application
      uses: actions/upload-artifact@v4
      with:
        name: matrix-eyes-${{ runner.os }}-${{ matrix.arch }}
        path: matrix-eyes-*.zip

  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        arch: [aarch64, x86_64]

    steps:
    - uses: actions/checkout@v4

    - name: Get current Rust version
      id: get-rust-version
      run: echo VERSION=$(rustc --version | sed s/\ /_/g) >> "$GITHUB_OUTPUT"

    - name: Cache Rust dependencies and artifacts
      id: cache-rust
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ${{ github.workspace }}/target
        key: rust-${{ runner.os }}-${{ matrix.arch }}-${{ steps.get-rust-version.outputs.VERSION }}-${{ hashFiles('Cargo.*') }}

    - name: Install compiler and prepare for cross-compilation
      if: matrix.arch == 'x86_64'
      run: rustup target add ${{ matrix.arch }}-apple-darwin

    - name: Build
      run: cargo build --target=${{ matrix.arch }}-apple-darwin --features=metal --release

    - name: Package application
      run: tar -cvjf matrix-eyes-${{ runner.os }}-${{ matrix.arch }}.tar.bz2 -C target/${{ matrix.arch }}-apple-darwin/release matrix-eyes

    - name: Upload application
      uses: actions/upload-artifact@v4
      with:
        name: matrix-eyes-${{ runner.os }}-${{ matrix.arch }}
        path: matrix-eyes-*.tar.bz2

  package:
    runs-on: ubuntu-latest
    needs: [ "build-linux", "build-windows", "build-macos" ]
    steps:
      - name: Merge all applications
        uses: actions/upload-artifact/merge@v4
        with:
          name: matrix-eyes-all
          pattern: matrix-eyes-*
