name: Cargo build

on:
  push:
    branches: [ "main", "rust" ]
  pull_request:
    branches: [ "main", "rust" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4

    - name: Get current Rust version
      id: get-rust-version
      run: echo VERSION=$(rustc --version | sed s/\ /_/g) >> "$GITHUB_OUTPUT"

    - name: Cache Rust dependencies and artifacts
      id: cache-rust
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ${{ github.workspace }}/target
        key: lint-${{ runner.os }}-${{ steps.get-rust-version.outputs.VERSION }}-${{ hashFiles('Cargo.*') }}

    - name: Validate Rust code with clippy
      run: cargo clippy

  build-linux:
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      fail-fast: true
      matrix:
        include:
        - arch: x86_64
          os: ubuntu
          acceleration: cuda
        - arch: x86_64
          os: ubuntu
          acceleration: wgpu-spirv
        - arch: aarch64
          os: ubuntu
          acceleration: ndarray

    steps:
    - uses: actions/checkout@v4

    - name: Get current Rust version
      id: get-rust-version
      run: echo VERSION=$(rustc --version | sed s/\ /_/g) >> "$GITHUB_OUTPUT"

    - name: Cache Rust dependencies and artifacts
      id: cache-rust
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ${{ github.workspace }}/target
        key: rust-${{ runner.os }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.acceleration }}-${{ steps.get-rust-version.outputs.VERSION }}-${{ hashFiles('Cargo.*') }}

    - name: Install compiler and prepare for cross-compilation
      if: matrix.arch == 'aarch64'
      run: |
        rustup target add ${{ matrix.arch }}-unknown-linux-gnu
        sudo apt-get update
        sudo apt-get install -y crossbuild-essential-arm64 qemu-user-static
        echo "LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CC=/usr/bin/aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX=/usr/bin/aarch64-linux-gnu-g++" >> $GITHUB_ENV
        echo "CFLAGS=-march=armv8.2-a" >> $GITHUB_ENV
        echo "CXXFLAGS=-march=armv8.2-a" >> $GITHUB_ENV

    - name: Install CUDA
      if: matrix.acceleration == 'cuda'
      run: |
        curl -LOJ https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update
        sudo apt-get -y install cuda-compiler-12-6 cuda-libraries-dev-12-6
        echo "/usr/local/cuda-12.6/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" >> $GITHUB_ENV
        echo "CUDA_COMPUTE_CAP=75" >> $GITHUB_ENV
        echo "CUDA_PATH=/usr/local/cuda-12.6" >> $GITHUB_ENV

    - name: Build
      run: cargo build --target=${{ matrix.arch }}-unknown-linux-gnu --no-default-features --features=${{ matrix.acceleration }} --release

    - name: Package application
      run: tar -cvjf matrix-eyes-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.acceleration }}.tar.bz2 -C target/${{ matrix.arch }}-unknown-linux-gnu/release matrix-eyes

    - name: Upload application
      uses: actions/upload-artifact@v4
      with:
        name: matrix-eyes-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.acceleration }}
        path: matrix-eyes-*.tar.bz2

  build-windows:
    runs-on: windows-latest
    needs: validate
    strategy:
      fail-fast: true
      matrix:
        include:
        - arch: x86_64
          acceleration: cuda
        - arch: x86_64
          acceleration: wgpu-spirv
        - arch: x86_64
          acceleration: ndarray
        - arch: aarch64
          acceleration: ndarray

    steps:
    - uses: actions/checkout@v4

    - name: Get current Rust version
      id: get-rust-version
      run: |
        $version = rustc --version | % {$_.replace(" ","_")}
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Cache Rust dependencies and artifacts
      id: cache-rust
      uses: actions/cache@v4
      with:
        path: |
          ~\.cargo\registry\index
          ~\.cargo\registry\cache
          ~\.cargo\git\db
          ${{ github.workspace }}\target
        key: rust-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.acceleration }}-${{ steps.get-rust-version.outputs.VERSION }}-${{ hashFiles('Cargo.*') }}

    - name: Install compiler and prepare for cross-compilation
      if: matrix.arch == 'aarch64'
      run: rustup target add ${{ matrix.arch }}-pc-windows-msvc

    - name: Install CUDA
      if: matrix.acceleration == 'cuda'
      run: |
        Invoke-WebRequest https://developer.download.nvidia.com/compute/cuda/12.6.3/network_installers/cuda_12.6.3_windows_network.exe -OutFile cuda_12.6.3_windows_network.exe
        $FileHash = Get-FileHash cuda_12.6.3_windows_network.exe -Algorithm MD5
        if ($FileHash.Hash -ne "48d5d66c3550b7744715c638dac4f522") {
          Write-Error "Download hash mismatch" -ErrorAction Stop
        }
        Start-Process -FilePath .\cuda_12.6.3_windows_network.exe -ArgumentList "-s nvcc_12.6 cudart_12.6" -Wait -NoNewWindow
        echo "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "CUDA_COMPUTE_CAP=75" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "CUDA_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        $version = Get-Content "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt" -Raw
        $version = $version.Trim()
        echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\$version\bin\HostX64\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build
      run: |
        cargo build --target=${{ matrix.arch }}-pc-windows-msvc --no-default-features --features=${{ matrix.acceleration }} --release

    - name: Package application
      run: Compress-Archive -Path .\target\${{ matrix.arch }}-pc-windows-msvc\release\matrix-eyes.exe -DestinationPath matrix-eyes-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.acceleration }}.zip

    - name: Upload application
      uses: actions/upload-artifact@v4
      with:
        name: matrix-eyes-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.acceleration }}
        path: matrix-eyes-*.zip

  build-macos:
    runs-on: macos-latest
    needs: validate
    strategy:
      fail-fast: true
      matrix:
        include:
        - arch: x86_64
          acceleration: wgpu
        - arch: x86_64
          acceleration: ndarray-accelerate
        - arch: aarch64
          acceleration: wgpu
        - arch: aarch64
          acceleration: ndarray-accelerate

    steps:
    - uses: actions/checkout@v4

    - name: Get current Rust version
      id: get-rust-version
      run: echo VERSION=$(rustc --version | sed s/\ /_/g) >> "$GITHUB_OUTPUT"

    - name: Cache Rust dependencies and artifacts
      id: cache-rust
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ${{ github.workspace }}/target
        key: rust-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.acceleration }}-${{ steps.get-rust-version.outputs.VERSION }}-${{ hashFiles('Cargo.*') }}

    - name: Install compiler and prepare for cross-compilation
      if: matrix.arch == 'x86_64'
      run: rustup target add ${{ matrix.arch }}-apple-darwin

    - name: Build
      run: cargo build --target=${{ matrix.arch }}-apple-darwin --no-default-features --features=${{ matrix.acceleration }} --release

    - name: Package application
      run: tar -cvjf matrix-eyes-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.acceleration }}.tar.bz2 -C target/${{ matrix.arch }}-apple-darwin/release matrix-eyes

    - name: Upload application
      uses: actions/upload-artifact@v4
      with:
        name: matrix-eyes-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.acceleration }}
        path: matrix-eyes-*.tar.bz2

  package:
    runs-on: ubuntu-latest
    needs: [ "build-linux", "build-windows", "build-macos" ]
    steps:
      - name: Merge all applications
        uses: actions/upload-artifact/merge@v4
        with:
          name: matrix-eyes-all
          pattern: matrix-eyes-*
